name: Update Website Nootes

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: C0de5mith/c0de5mith.github.io
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
      
      - name: Pull & Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions - Update Website Notes"
          git add --all
          git commit -m "Update Website Notes" || echo "No changes"
          git push
